postgres:
  host: postgres
  port: 5432
  database: india_finance_db
  user: etl_user
  password: etl_password
  table: india_personal_finance
  
connection:
  driver: org.postgresql.Driver
  url: jdbc:postgresql://postgres:5432/india_finance_db
  
query:
  select_all: "SELECT * FROM india_personal_finance"
  batch_size: 1000