spark:
  app_name: India_Finance_UPI_ETL
  master: spark://spark-master:7077
  
  # Spark configurations
  config:
    spark.sql.warehouse.dir: /opt/hive-data/warehouse
    spark.sql.hive.metastore.uris: thrift://hive-metastore:9083
    spark.sql.adaptive.enabled: true
    spark.sql.adaptive.coalescePartitions.enabled: true
    spark.sql.shuffle.partitions: 200
    
  # Packages (Spark 3.3.2)
  packages:
    - org.apache.spark:spark-sql-kafka-0-10_2.12:3.3.2
    - org.postgresql:postgresql:42.6.0
    
# Spark application configuration
application:
  name: India_Finance_UPI_ETL
  executor_memory: 2g
  driver_memory: 2g
  executor_cores: 2
  num_executors: 2
  
# Data paths
paths:
  raw_data: /opt/spark-data/raw
  processed_data: /opt/spark-data/processed/spark
  clean_data: /opt/spark-data/processed/spark/clean
  rejected_data: /opt/spark-data/processed/spark/rejected
  logs: /opt/spark-logs
